#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
MyConfig="\
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend web-servers
    
backend web-servers
    balance roundrobin
    server 26580-web-01	34.239.163.172:80
    server 26580-web-02	3.236.247.121:80
"
add-apt-repository ppa:vbernat/haproxy-2.0
apt update
apt install -y haproxy
echo "$MyConfig" >> /etc/haproxy/haproxy.cfg
service haproxy start